# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session: false

    http_client:
        scoped_clients:
            coinpaprika.client:
                base_uri: '%env(string:COINPAPRIKA_BASE_URL)%'
            floatrates.client:
                base_uri: '%env(string:FLOATRATES_BASE_URL)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
