services:

    cli:
        tty: true
        command:
            - sh
        container_name: converter
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app:z
        environment:
            COINPAPRIKA_BASE_URL: https://api.coinpaprika.com/
            FLOATRATES_BASE_URL: https://www.floatrates.com/
